dist: focal
sudo: required
language: python
services:
  - mongodb
  - docker

python:
  - "3.8"

cache: pip

virtualenv:
  system_site_packages: true

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: test
    - language: python
      python: 3.8
      script:
        - pytest --cov=./

    - language: python
      python: 3.8
      script:
        - pylint --fail-under 8 application config.py pet user wsgi.py test

stages:
  - name: test
    # require the type to be a PR
    if: type = pull_request
  - name: deploy
    # require the type to be push to master
    if: type = push AND branch = master

deploy:
  on:
    branch: master
    script:
      docker-compose build
      echo "$DOCKER_USERNAME" | docker login -u "$DOCKER_PASSWORD" --password-stdin
      docker push sharidasan/petshotel
