apiVersion: v1
kind: Service
metadata:
    name: flask-service
spec:
    type: NodePort
    ports:
        - port: 5000
          name: flask-app-port
          targetPort: 5000
          nodePort: 31515
    selector:
        component: web

