# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set up Mongodb
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with pylint
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pylint --fail-under 8 application config.py pet user wsgi.py test
    - name: Test with pytest
      run: |
        pytest
    - name: Docker login and push
      if: github.event.pull_request.merged == 'true'
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.D_U_NAME }}
        password: ${{ secrets.D_U_PASSWD }}
        repository: sharidasan/petshotel
