name: python package

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master
    

jobs:
    build:

        runs-on: ubuntu-latest
        strategy:
        matrix:
            python-version: [3.6, 3.8]
        

        steps:
        - uses: actions/checkout@v2
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: Lint with pylint
          run: |
          pylint --fail-under 8 application config.py pet user wsgi.py test
