# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Docker Integration

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set up Mongodb
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Docker login and push
      run: |
        docker-compose build
        echo ${{ secrets.D_U_PASSWD }} | docker login -u ${{ secrets.D_U_NAME }} --password-stdin
        docker push sharidasan/petshotel
